// <auto-generated />
using System;
using Calender_WebApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calender_WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209205227_RemindersPreference_Primairy_not_generated")]
    partial class RemindersPreference_Primairy_not_generated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Calender_WebApp.Models.AdminsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("admin_id")
                        .HasColumnOrder(0)
                        .HasAnnotation("Relational:JsonPropertyName", "admin_id");

                    b.Property<int>("Permissions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("permissions")
                        .HasColumnOrder(2);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("Calender_WebApp.Models.EmployeesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0)
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password")
                        .HasColumnOrder(4);

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Calender_WebApp.Models.EventParticipationModel", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_id");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("eventparticipation");
                });

            modelBuilder.Entity("Calender_WebApp.Models.EventsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_id")
                        .HasColumnOrder(0)
                        .HasAnnotation("Relational:JsonPropertyName", "event_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_date")
                        .HasColumnOrder(3);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Calender_WebApp.Models.GroupMembershipsModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_id");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("groupmemberships");
                });

            modelBuilder.Entity("Calender_WebApp.Models.GroupsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_id")
                        .HasColumnOrder(0)
                        .HasAnnotation("Relational:JsonPropertyName", "group_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description")
                        .HasColumnOrder(2);

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_name")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("Calender_WebApp.Models.OfficeAttendanceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("attendance_id")
                        .HasColumnOrder(0)
                        .HasAnnotation("Relational:JsonPropertyName", "attendance_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date")
                        .HasColumnOrder(2);

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status")
                        .HasColumnOrder(3);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("officeattendance");
                });

            modelBuilder.Entity("Calender_WebApp.Models.ReminderPreferencesModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0)
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<bool>("BookingReminder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("booking_reminder")
                        .HasColumnOrder(2);

                    b.Property<bool>("EventReminder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_reminder")
                        .HasColumnOrder(1);

                    b.Property<TimeSpan>("ReminderAdvanceMinutes")
                        .HasColumnType("TEXT")
                        .HasColumnName("reminder_advance_minutes")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("reminderpreferences");
                });

            modelBuilder.Entity("Calender_WebApp.Models.RemindersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("reminder_id")
                        .HasColumnOrder(0)
                        .HasAnnotation("Relational:JsonPropertyName", "reminder_id");

                    b.Property<bool>("IsSent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_sent")
                        .HasColumnOrder(7);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message")
                        .HasColumnOrder(9);

                    b.Property<int>("RelatedEventId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("related_event_id")
                        .HasColumnOrder(5);

                    b.Property<int>("RelatedRoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("related_room_id")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("reminder_time")
                        .HasColumnOrder(6);

                    b.Property<int>("ReminderType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reminder_type")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .HasColumnOrder(8);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("reminders");
                });

            modelBuilder.Entity("Calender_WebApp.Models.RoomBookingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("booking_id")
                        .HasAnnotation("Relational:JsonPropertyName", "booking_id");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("booking_date")
                        .HasColumnOrder(2);

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time")
                        .HasColumnOrder(4);

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose")
                        .HasColumnOrder(5);

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_id")
                        .HasColumnOrder(0);

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time")
                        .HasColumnOrder(3);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("roombookings");
                });

            modelBuilder.Entity("Calender_WebApp.Models.RoomsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_id")
                        .HasColumnOrder(0)
                        .HasAnnotation("Relational:JsonPropertyName", "room_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity")
                        .HasColumnOrder(2);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location")
                        .HasColumnOrder(3);

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("room_name")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Calender_WebApp.Models.AdminsModel", b =>
                {
                    b.HasOne("Calender_WebApp.Models.EmployeesModel", "Employee")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Calender_WebApp.Models.EventParticipationModel", b =>
                {
                    b.HasOne("Calender_WebApp.Models.EventsModel", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calender_WebApp.Models.EmployeesModel", "Employee")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Calender_WebApp.Models.EventsModel", b =>
                {
                    b.HasOne("Calender_WebApp.Models.EmployeesModel", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Calender_WebApp.Models.GroupMembershipsModel", b =>
                {
                    b.HasOne("Calender_WebApp.Models.GroupsModel", "Group")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calender_WebApp.Models.EmployeesModel", "Employee")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Calender_WebApp.Models.OfficeAttendanceModel", b =>
                {
                    b.HasOne("Calender_WebApp.Models.EmployeesModel", "Employee")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Calender_WebApp.Models.RoomBookingsModel", b =>
                {
                    b.HasOne("Calender_WebApp.Models.RoomsModel", "Room")
                        .WithMany("RoomBookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calender_WebApp.Models.EmployeesModel", "Employee")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Calender_WebApp.Models.GroupsModel", b =>
                {
                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("Calender_WebApp.Models.RoomsModel", b =>
                {
                    b.Navigation("RoomBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
